services:
  zookeeper:
    image: 'wurstmeister/zookeeper:latest'
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - '2181:2181'
  kafka:
    image: 'wurstmeister/kafka:latest'
    container_name: kafka
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
    ports:
      - '9092:9092'
    depends_on:   
      - zookeeper
  spring-boot-learning:
    image: 'spring-boot-learning:1.0'
    container_name: spring-boot-learning-container
    environment:
      - SPRING_PROFILES_ACTIVE=test
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
    ports:
      - '8080:8080'
    depends_on:
      - kafka
      - rabbitmq
  rabbitmq:
    image: 'rabbitmq:4.1.4-management'
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
      - '25672:25672'