testing.value: test profile loaded
logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    com.example: TRACE
  file:
    name: logs/myapp.log
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    username: root
    password: welcome123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: employee-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
  cache:
    type: hazelcast

management:
  endpoints:
    web:
      exposure:
        include: "*"
